spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE:local}
      uri: ${MONGODB_URI:mongodb://localhost:27017}
  rabbitmq:
    addresses: ${MQ_ADDRESSES:amqps://localhost:5672}
  banner:
    location: classpath:banner.txt

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    com.github.bucket4j: DEBUG
    com.ced: DEBUG

cors:
  allowed-origins:
    - https://characters.discloud.app
    - http://localhost:4200
    - https://cavernas-e-dragoes.web.app

security:
  token: ${TOKEN_PASSWORD:xD}
  expiration: ${TOKEN_EXPIRATION:6000000}

amqp:
  exchange-name: ${EXCHANGE_NAME:xD}
  queue-name: ${QUEUE_NAME:xD}
  routing-key: ${ROUTING_KEY:xD}

application:
  base-url: ${BASE_URL:http://localhost:8080}
  verification:
    token:
      expiry-minutes: ${VERIFICATION_TOKEN_EXPIRY:1440}
    resend-hours: ${VERIFICATION_RESEND_HOURS:24}